### ISSUE TITLE
Some results from testing.

### ISSUE THREAD

**Issue by NullCase** [Phoenix616/CheaperPhysicsEvent#2]
config:
```
plugins:
- ChestShop
- WorldGuard
```

Confounding variables: 

- reports are 4 days apart. 
- The count for both events is far lower. Could be changes in player activity OR something in the plugin.
- The _after_ report has roughly 21% fewer tile entities and 17% fewer entities.

**Before plugin:**
https://timings.aikar.co/?id=5df93974585e44f4a8cf582127764605#timings

```
WorldGuard::Event: c.s.w.b.l.WorldGuardBlockListener (BlockPhysicsEvent)count(255743071)  total(1.41% 35.872s, 1.03% of tick)avg(0.00ms per - 0.51ms/3,660.58 per tick)
ChestShop::Event: c.A.C.L.B.B.SignBreak (BlockPhysicsEvent)count(255743071)  total(1.39% 35.476s, 1.02% of tick)avg(0.00ms per - 0.51ms/3,660.58 per tick)
```
Note: both were reporting quite low here. It's gone as high as 40% and 18% respectively just under normal play conditions.

**After plugin:**
https://timings.aikar.co/?id=4498288417e64c378fd1abdcf48ede62

```
WorldGuard::Event: c.s.w.b.l.WorldGuardBlockListener (BlockPhysicsEvent)count(2894)  total(0.00% 0.004s, 0.00% of tick)avg(0.00ms per - 0.00ms/0.04 per tick)
ChestShop::Event: c.A.C.L.B.B.SignBreak (BlockPhysicsEvent)count(2894)  total(0.00% 0.003s, 0.00% of tick)avg(0.00ms per - 0.00ms/0.04 per tick)
```
Note: I have never observed either event to use more than 0.04% of a tick during testing.

Conclusions:

- Plugin lag caused by physics updates is approximately 0, but the count is down 10,000 fold. Unclear what's causing that huge drop in event count.
- Sending payment now. It reflects how much money this update will save me (delays the point in time where we might have to upgrade to a larger server). Provided this remains functional after 1.14 I can afford another payment.

https://www.libertyminecraft.com/cheaperphysicsevent-by-phoenix616/

**Comment by Phoenix616** [comment]
Thanks, dude! Didn't really do it expecting anything for it but it definitely is appreciated! :D Also even though this plugin exists now it's really only a quite hacky quick fix and I will definitly look into improving this directly in ChestShop (and maybe through another plugin/server modification) so stuff like this isn't necessary anymore.

For anyone else stumbling over this please also read my [comment](https://github.com/ChestShop-authors/ChestShop-3/issues/214#issuecomment-479509363) on the original ChestShop issue regarding compatibility with plugins before using this plugin!

**Comment by NullCase** [comment]
A quick fix. OK, it sounds like this might be directly added to ChestShop later. How about LMC runs CheaperPhysicsEvent and we'll see how we can break it.

Do you want me to post here if anything interesting pops up?

**Comment by Phoenix616** [comment]
Sure, feel free to report anything that looks interesting.

**Comment by NullCase** [comment]
Hi @Phoenix616 This plugin runs flawlessly in 1.13.2. We've used it every day since with no issues to be found.
