### ISSUE TITLE
CheaperEvents for:

### ISSUE THREAD

**Issue by NullCase** [Phoenix616/CheaperPhysicsEvent#3]
Hi Phoenix616,

While testing something popped out. It looks like other events are quite laggy. Here are two events called by GriefPrevention.

Do you think these are using Paper?

```
GriefPrevention::Event: m.r.G.BlockEventHandler (BlockPistonRetractEvent)count(6135)  total(34.26% 3.462s, 92.31% of tick)avg(0.56ms per - 46.16ms/81.80 per tick
GriefPrevention::Event: m.r.G.PlayerEventHandler (PlayerPortalEvent)count(2)  total(11.36% 1.148s, 30.61% of tick)avg(573.86ms per - 15.30ms/0.03 per tick)
```

**Comment by Phoenix616** [comment]
Paper doesn't have better replacements for these as far as I know. Your only option might be to disable protection against portals/pistons if GriefPrevention supports that.

**Comment by Phoenix616** [comment]
Paper doesn't have better replacements for these as far as I know. Your only option might be to disable protection against portals/pistons if GriefPrevention supports that.

**Comment by NullCase** [comment]
no better replacement. OK.

it sounds like I didn't understand so well what you had created when this was first posted.

Now, pretty sure you've just used another event to check for sign breaks which isn't used as often as physics events. Still, that small change has made a big difference.

I've spoken with RoboMWM about pistons, so maybe that route will work.

Thanks @Phoenix616
